version: 2.1
orbs:
  ci-actions: senormann/ci-actions@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - ci-actions/greet
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - ci-actions/bump-version-and-upload-artifact:
          app-dir: "~/project/samples/node-app"
          dry_run: true
          filters: *filters
          git_user_email: $GIT_USER_EMAIL
          git_user_name: $GIT_USER_NAME
          npm_registry: $NPM_REGISTRY
          npm_registry_auth: $NPM_REGISTRY_AUTH
          npm_registry_email: $NPM_REGISTRY_EMAIL
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: senormann/ci-actions
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
            - ci-actions/bump-version-and-upload-artifact
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
